name: Build Docker image arm64

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  shadowbox:
    name: Shadowbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
    
      - name: Build Docker Image
        run: ./task shadowbox:docker:buildx IMAGE_VERSION=${{ github.ref_name }} TARGET_ARCH=arm64 IMAGE_NAME=${{ env.IMAGE_NAME }}

      - name: Push Docker Image version ${{ github.ref_name }}
        run: docker push ${{ env.REGISTRY}}/${{ env.IMAGE_NAME}}:${{ github.ref_name }}

      - name: Push Docker Image latest
        run: docker push ${{ env.REGISTRY}}/${{ env.IMAGE_NAME}}:latest
