name: Build and Test Docker image arm64

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Lint
        run: ./task lint

  shadowbox:
    name: Shadowbox
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Shadowbox Debug Build
        run: ./task shadowbox:build

      - name: Shadowbox Unit Test
        run: ./task shadowbox:test

      - name: Shadowbox Integration Test
        run: ./task shadowbox:integration_test

      - name: Verify Open API Spec
        uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            src/shadowbox/server/api.yml

      - name: Build Docker Image
        run: ./task shadowbox:docker_build IMAGE_VERSION=${{ github.ref_name }} TARGET_ARCH=arm64 IMAGE_NAME=artemkiyashko/shadowbox

      - name: Push Docker Image version ${{ github.ref_name }}
        run: docker push ghcr.io/artemkiyashko/shadowbox:${{ github.ref_name }}

      - name: Push Docker Image latest
        run: docker push ghcr.io/artemkiyashko/shadowbox:latest
